@startuml
left to right direction

!$stakeholder = "<stakeholder>"
!$painpoint = "<pain point>"

!$actor = "<user>"
!$behavior = "<behavior>"
!$rationale = "<rationale>"

object stakeholderconcern1 {
    As a $stakeholder
    I experience $painpoint
}

object userstory1 {
    As a $actor
    I want to $behavior
    so that I can $rationale
}
note bottom of userstory1 : <b>Example:</b> $behavior using some standard

stakeholderconcern1 <.. userstory1 : <<trace>>
@enduml
